version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_mongo_data: {}


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: interview_task_django
    container_name: interview_task_django
    depends_on:
      - postgres
    volumes:
      - .:/app:cached
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
      - ./.envs/.local/.mongo
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: interview_task_postgres
    container_name: interview_task_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:cached
      - local_postgres_data_backups:/backups:cached
    env_file:
      - ./.envs/.local/.postgres
  
  mongodb:
    image: mongo:4.4
    container_name: interview_task_mongo
    volumes:
      - local_mongo_data:/data/db:cached  
    ports:
      - "27017:27017"  
    env_file:
      - ./.envs/.local/.mongo
