# Generated by Django 4.1.5 on 2024-11-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_mongomenu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='qr_code',
        ),
    ]
