# Generated by Django 4.1.5 on 2024-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_mongomenu'),
        ('order', '0002_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MongoOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postgres_id', models.IntegerField(unique=True)),
                ('order_id', models.IntegerField()),
                ('menu_item_id', models.IntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MongoOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postgres_id', models.IntegerField(unique=True)),
                ('user_id', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=25)),
                ('menu_items', models.ManyToManyField(to='menu.menu')),
            ],
        ),
    ]
